// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfB46mC2vsDrkD-SyeDn5M0S2UMToAhfE',
    appId: '1:811520328243:web:9455db0d6d24a6d12f5946',
    messagingSenderId: '811520328243',
    projectId: 'family-hearth-home',
    authDomain: 'family-hearth-home.firebaseapp.com',
    storageBucket: 'family-hearth-home.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfdqvyN5DM-7fPrwTiH6Gt_MJ8dwAsWkw',
    appId: '1:811520328243:android:58310bfb74df71762f5946',
    messagingSenderId: '811520328243',
    projectId: 'family-hearth-home',
    storageBucket: 'family-hearth-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlyTHjQp9bwynMjxwtVThA6nByypRdORY',
    appId: '1:811520328243:ios:89400ee2f8d1657d2f5946',
    messagingSenderId: '811520328243',
    projectId: 'family-hearth-home',
    storageBucket: 'family-hearth-home.firebasestorage.app',
    iosBundleId: 'com.nihad.familyhearth',
  );
}
